CREATE EXTERNAL TABLE [dbo].[ETB_DIM_EVENT_TYPE] (
    [EVENT_TYPE_KEY] VARCHAR (8000) NULL,
    [SRC_SYSTEM_CODE] VARCHAR (8000) NULL,
    [EVENT_NAME] VARCHAR (8000) NULL,
    [SRC_EVENT_TYPE] VARCHAR (8000) NULL,
    [GENERIC_EVENT_NAME] VARCHAR (8000) NULL,
    [GENERIC_EVENT_GROUP] VARCHAR (8000) NULL,
    [MI_EVENT_GROUP] VARCHAR (8000) NULL,
    [SRC_SYSTEM_CASE_TYPE_NAME] VARCHAR (8000) NULL
)
    WITH (
    DATA_SOURCE = [EDS_DIM_TBL],
    LOCATION = N'/DIM_EVENT_TYPE.csv',
    FILE_FORMAT = [TextFileFormat],
    REJECT_TYPE = VALUE,
    REJECT_VALUE = 0
    );

