CREATE EXTERNAL TABLE [dbo].[ETB_MDM_PROBATE_LOCATION_LU] (
    [CE_REG_LOCATION] VARCHAR (8000) NULL,
    [LOCATION_KEY] VARCHAR (8000) NULL
)
    WITH (
    DATA_SOURCE = [EDS_DIM_TBL],
    LOCATION = N'/MDM_PROBATE_LOCATION_LU.csv',
    FILE_FORMAT = [TextFileFormat],
    REJECT_TYPE = VALUE,
    REJECT_VALUE = 0
    );

