CREATE EXTERNAL TABLE [dbo].[ETB_DIM_CASE_TYPE] (
    [CASE_TYPE_CODE] VARCHAR (8000) NULL,
    [SOURCE_SYSTEM_CODE] VARCHAR (8000) NULL,
    [CASE_TYPE_DESCRIPTOR] VARCHAR (8000) NULL,
    [MAJOR_CASE_TYPE] VARCHAR (8000) NULL,
    [MINOR_CASE_TYPE] VARCHAR (8000) NULL,
    [CASE_TYPE_KEY] VARCHAR (8000) NULL,
    [GENERIC_CASE_TYPE] VARCHAR (8000) NULL,
    [HIGH_COURT] VARCHAR (8000) NULL,
    [JURISDICTION_KEY] VARCHAR (8000) NULL
)
    WITH (
    DATA_SOURCE = [EDS_DIM_TBL],
    LOCATION = N'/DIM_CASE_TYPE.csv',
    FILE_FORMAT = [TextFileFormat],
    REJECT_TYPE = VALUE,
    REJECT_VALUE = 0
    );

