CREATE EXTERNAL TABLE [dbo].[ETB_MDM_EVENT_TYPE_GRP] (
    [EVENT_TYPE_GRP_KEY] VARCHAR (8000) NULL,
    [EVENT_TYPE_GRP_NAME] VARCHAR (8000) NULL,
    [EVENT_TYPE_GRP_DESC] VARCHAR (8000) NULL,
    [BIS_FIRST_CREATED_DATETIME] VARCHAR (8000) NULL,
    [BIS_LAST_MODIFIED_DATETIME] VARCHAR (8000) NULL,
    [MODIFIED_BY_PROCESS_NAME] VARCHAR (8000) NULL,
    [INSERTED_BY_PROCESS_NAME] VARCHAR (8000) NULL
)
    WITH (
    DATA_SOURCE = [EDS_DIM_TBL],
    LOCATION = N'/MDM_EVENT_TYPE_GRP.csv',
    FILE_FORMAT = [TextFileFormat],
    REJECT_TYPE = VALUE,
    REJECT_VALUE = 0
    );

