CREATE TABLE [dbo].[FCT_PROBATE_SUMMARY] (
    [DATE_KEY]                       DATETIME        NOT NULL,
    [SOURCE_KEY]                     DECIMAL (10, 6) NOT NULL,
    [LOCATION_KEY]                   DECIMAL (10, 6) NOT NULL,
    [CASE_TYPE_KEY]                  DECIMAL (10, 6) NOT NULL,
    [PROBATE_APPLCTN_TYPE_KEY]       DECIMAL (10, 6) NOT NULL,
    [SUBMITTED]                      FLOAT (53)      NULL,
    [ISSUED]                         FLOAT (53)      NULL,
    [DAYS_SUBMITTED_TO_ISSUED]       FLOAT (53)      NULL,
    [EXAMINED]                       FLOAT (53)      NULL,
    [STOPPED]                        FLOAT (53)      NULL,
    [TOTAL_CASES]                    FLOAT (53)      NULL,
    [ISSUED_IN_20DAYS]               FLOAT (53)      NULL,
    [ISSUED_IN_7WDAYS]               FLOAT (53)      NULL,
    [CAVEAT_COUNT]                   FLOAT (53)      NULL,
    [WLGMT_COUNT]                    FLOAT (53)      NULL,
    [STANDING_SEARCH_COUNT]          FLOAT (53)      NULL,
    [TOTAL_CASE_STOPS_COUNT]         INT             NULL,
    [RGSTR_ESCLTN_CASE_COUNT]        INT             NULL,
    [RGSTR_ESCLTN_TOTAL_COUNT]       BIGINT          NULL,
    [RGSTR_ESCLTN_DAYS_COUNT]        BIGINT          NULL,
    [CAVEAT_ACTIVE_COUNT]            BIGINT          NULL,
    [GRANT_ISSUE_RGSTR_ESCLTN_COUNT] INT             NULL,
    [REISSUED_RGSTR_DIRCTN_COUNT]    INT             NULL,
    [REISSUED_RGSTR_ORDER_COUNT]     INT             NULL,
    [REISSUED_DUPLCT_COUNT]          INT             NULL,
    [REISSUED_TOTAL_COUNT]           INT             NULL,
    [WTHDRWN_TOTAL_COUNT]            INT             NULL,
    [WTHDRWN_FOR_PROVING_COUNT]      INT             NULL,
    [WTHDRWN_TESTATOR_COUNT]         INT             NULL,
    [WTHDRWN_CANCELLED_COUNT]        INT             NULL,
    [CASE_SRCH_MATCHED_COUNT]        INT             NULL,
    [REISSUE_PENDING_COUNT]          INT             NULL,
    [ISSUED_WTHN_2WRKGDY_COUNT]      INT             NULL,
    [EXPRD_TOTAL_COUNT]              INT             NULL,
    [CASE_FEE_PAYABLE_COUNT]         INT             NULL,
    [GRANT_APPLCTN_WTHDRWN_COUNT]    INT             NULL,
    [SUBMSN_TO_DOC_RECPT_DAYS_COUNT] BIGINT          NULL,
    [DOC_RECPT_TO_ISSUE_DAYS_COUNT]  BIGINT          NULL,
    [SUBMSN_TO_DOC_RECPT_WKDY_COUNT] BIGINT          NULL,
    [DOC_RECPT_TO_ISSUE_WKDY_COUNT]  BIGINT          NULL,
    [SUBMSN_TO_ISSUE_WKDY_COUNT]     BIGINT          NULL,
    [DOC_RECVD_COUNT]                INT             NULL,
    [WRK_RESTRT_FROM_STOP_COUNT]     INT             NULL,
    [FRST_STOP_RESTRT_WRKDY_DURTN]   INT             NULL,
    [WRK_STRTD_COUNT]                INT             NULL,
    [DOC_RECVD_TO_STRTD_WRKDY_DURTN] INT             NULL,
    [DOC_RECVD_STRTD_2WRKDY_COUNT]   INT             NULL,
    [GRANT_APPLCTN_OUTSTNDNG_COUNT]  INT             NULL,
    [DOC_RECVD_ISSUE_7WRKDY_COUNT]   INT             NULL,
    [PREFRD_LANG_TYPE_KEY]           DECIMAL (10, 6) NOT NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = ROUND_ROBIN);

