CREATE TABLE [dbo].[MDM_LEGAL_CASE_STATE_TYPE_LU] (
    [LEGAL_CASE_STATE_TYPE_CID]    VARCHAR (50)    NULL,
    [LEGAL_CASE_STATE_TYPE_KEY]    DECIMAL (10, 6) NULL,
    [LEGAL_CASE_STATE_TYPE_NAME]   VARCHAR (50)    NOT NULL,
    [SOURCE_SYSTEM_CASE_TYPE_NAME] VARCHAR (50)    NULL,
    [CCD_CASE_TYPE_NAME]           VARCHAR (50)    NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = ROUND_ROBIN);

