CREATE TABLE [dbo].[MDM_PROBATE_CASE_TYPE_LU] (
    [CE_GOR_CASE_TYPE] VARCHAR (100)   NULL,
    [CASE_TYPE_KEY]    DECIMAL (10, 6) NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = ROUND_ROBIN);

