CREATE TABLE [dbo].[MDM_PROBATE_APPLCTN_TYPE_LU] (
    [PROBATE_APPLCTN_TYPE_KEY]      DECIMAL (10, 6) NULL,
    [APPLCTN_SUBMTD_ROLE_TYPE_NAME] VARCHAR (50)    NULL,
    [APPLCTN_PAPERFORM_IND]         VARCHAR (50)    NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = ROUND_ROBIN);

