CREATE TABLE [dbo].[MDM_JURSDCTN_TYPE_LU] (
    [JURSDCTN_TYPE_CODE] VARCHAR (20)    NOT NULL,
    [JURSDCTN_TYPE_NAME] VARCHAR (250)   NULL,
    [JURSDCTN_TYPE_KEY]  DECIMAL (10, 6) NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = ROUND_ROBIN);

