CREATE EXTERNAL TABLE [dbo].[ETB_MDM_PROBATE_APPLCTN_TYPE_LU] (
    [PROBATE_APPLCTN_TYPE_KEY] VARCHAR (8000) NULL,
    [APPLCTN_SUBMTD_ROLE_TYPE_NAME] VARCHAR (8000) NULL,
    [APPLCTN_PAPERFORM_IND] VARCHAR (8000) NULL
)
    WITH (
    DATA_SOURCE = [EDS_DIM_TBL],
    LOCATION = N'/MDM_PROBATE_APPLCTN_TYPE_LU.csv',
    FILE_FORMAT = [TextFileFormat],
    REJECT_TYPE = VALUE,
    REJECT_VALUE = 0
    );

