CREATE EXTERNAL TABLE [dbo].[ETB_MDM_PROBATE_CASE_TYPE_LU] (
    [CE_GOR_CASE_TYPE] VARCHAR (8000) NULL,
    [CASE_TYPE_KEY] VARCHAR (8000) NULL
)
    WITH (
    DATA_SOURCE = [EDS_DIM_TBL],
    LOCATION = N'/MDM_PROBATE_CASE_TYPE_LU.csv',
    FILE_FORMAT = [TextFileFormat],
    REJECT_TYPE = VALUE,
    REJECT_VALUE = 0
    );

