CREATE EXTERNAL TABLE [dbo].[ETB_MDM_CCD_CASE_TYPE_LU] (
    [CCD_SRC_CASE_TYPE_NAME] VARCHAR (8000) NULL,
    [CCD_JURSDCTN_TYPE_NAME] VARCHAR (8000) NULL,
    [CCD_CASE_TYPE_NAME] VARCHAR (8000) NULL
)
    WITH (
    DATA_SOURCE = [EDS_DIM_TBL],
    LOCATION = N'/MDM_CCD_CASE_TYPE_LU.csv',
    FILE_FORMAT = [TextFileFormat],
    REJECT_TYPE = VALUE,
    REJECT_VALUE = 0
    );

