CREATE TABLE [dbo].[DIM_CASE_TYPE2] (
    [CASE_TYPE_CODE]       VARCHAR (100)   NOT NULL,
    [SOURCE_SYSTEM_CODE]   VARCHAR (5)     NOT NULL,
    [CASE_TYPE_DESCRIPTOR] VARCHAR (100)   NULL,
    [MAJOR_CASE_TYPE]      VARCHAR (50)    NULL,
    [MINOR_CASE_TYPE]      VARCHAR (50)    NULL,
    [CASE_TYPE_KEY]        DECIMAL (10, 6) NOT NULL,
    [GENERIC_CASE_TYPE]    VARCHAR (100)   NULL,
    [HIGH_COURT]           CHAR (1)        NULL,
    [JURISDICTION_KEY]     DECIMAL (10, 6) NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = ROUND_ROBIN);

