CREATE VIEW [V_LEGAL_PROBATE_CASE_EVENT]
AS SELECT "LEGAL_CASE_ID",

    "LEGAL_CASE_STATE_TYPE_CODE",

    "LEGAL_CASE_EVENT_ID",

    "EVENT_CREATED_TIMESTAMP",

    "LEGAL_CASE_TYPE_NAME",

    "LEGAL_CASE_TYPE_VRSN_NBR",

    "LEGAL_CASE_EVENT_TYPE_NAME",

    "LEGAL_CASE_STATE_TYPE_NAME",

    "LEGAL_CASE_STATE_CHANGE_NAME",

    "NEXT_EVENT_CREATED_TIMESTAMP",

    "NEXT_LEGAL_CASE_EVENT_ID",

    "NEXT_STATE_CREATED_TIMESTAMP",

    "NEXT_LEGAL_CASE_STATE_CODE",

    "BIS_FIRST_CREATED_DATETIME",

    "BIS_LAST_MODIFIED_DATETIME",

    "MODIFIED_BY_PROCESS_NAME",

    "INSERTED_DATETIME",

    "INSERTED_BY_PROCESS_NAME",

    "SOURCE_SYSTEM_TYPE_CODE",

    "LEGAL_CASE_EVENT_TYPE_CID",

    "USER_CID",

    "USER_FORENAME",

    "USER_SURNAME",

    "LEGAL_CASE_EVENT_TYPE_KEY",

    "LEGAL_CASE_STATE_TYPE_KEY",

    "JURISDICTION_KEY",

    "JURISDICTION_NAME",

    "LEGAL_CASE_REFERENCE_ID",

    "LEGAL_CASE_CREATED_TIMESTAMP"

  FROM v_legal_probate_jur_event

  WHERE legal_case_type_name IN ('GrantOfRepresentation', 'Caveat', 'WillLodgement', 'StandingSearch');