CREATE EXTERNAL FILE FORMAT [TextFileFormat]
    WITH (
    FORMAT_TYPE = DELIMITEDTEXT,
    FORMAT_OPTIONS (FIELD_TERMINATOR = N',', STRING_DELIMITER = N'"', DATE_FORMAT = N'yyyy-MM-dd', FIRST_ROW = 2, ENCODING = N'UTF8')
    );

